"""
Report Generator — builds Markdown diagnostic reports for export.
"""

from __future__ import annotations

import logging
from datetime import datetime
from typing import Any

from app.schemas.report import ReportData

logger = logging.getLogger(__name__)


class ReportGenerator:
    """Generates exportable diagnostic session reports."""

    def generate_markdown(self, data: ReportData) -> str:
        """Generate a Markdown-formatted diagnostic report."""
        lines = [
            "# TORQ Diagnostic Report",
            "",
            f"**Session ID:** `{data.session_id}`",
            f"**Date:** {data.created_at.strftime('%Y-%m-%d %H:%M UTC')}",
            "",
            "---",
            "",
            "## Vehicle Information",
            "",
            f"| Field | Value |",
            f"|-------|-------|",
            f"| VIN | {data.truck_vin} |",
            f"| Brand | {data.truck_brand} |",
            f"| Model | {data.truck_model} |",
            f"| Year | {data.truck_year} |",
            "",
            "## Complaint",
            "",
            f"**Symptom:** {data.symptom_text}",
            "",
            f"**DTC Codes:** {', '.join(data.dtc_codes)}",
            "",
            "---",
            "",
            "## Diagnostic Tests Performed",
            "",
        ]

        if data.tests_performed:
            lines.append("| # | Test | Result | Notes |")
            lines.append("|---|------|--------|-------|")
            for i, test in enumerate(data.tests_performed, 1):
                test_desc = test.get("description", test.get("test_id", "—"))
                result = test.get("result", "—")
                notes = test.get("notes", "")
                lines.append(f"| {i} | {test_desc} | {result} | {notes} |")
        else:
            lines.append("*No diagnostic tests were performed.*")

        lines.extend([
            "",
            "---",
            "",
            "## Diagnosis Result",
            "",
        ])

        if data.root_cause:
            lines.append(f"**Root Cause:** {data.root_cause}")
            lines.append(f"")
            lines.append(f"**Confidence Score:** {data.confidence_score:.1f}")
        else:
            lines.append("**Status:** Diagnosis incomplete or escalated")

        if data.cost_estimate:
            lines.extend([
                "",
                "---",
                "",
                "## Repair Cost Estimate",
                "",
            ])
            cost = data.cost_estimate
            parts = cost.get("parts", [])
            if parts:
                lines.append("### Parts")
                lines.append("| Part # | Description | Unit Price | Qty | Total |")
                lines.append("|--------|-------------|-----------|-----|-------|")
                for p in parts:
                    lines.append(
                        f"| {p.get('part_number', '—')} | {p.get('description', '—')} "
                        f"| ₹{p.get('price', 0):,.2f} | {p.get('quantity', 1)} "
                        f"| ₹{p.get('line_total', 0):,.2f} |"
                    )

            labor_hours = cost.get("labor_hours", 0)
            labor_rate = cost.get("labor_rate_per_hour", 800)
            consumables = cost.get("consumables", 0)
            total = cost.get("total", 0)

            lines.extend([
                "",
                "### Summary",
                "",
                f"| Component | Amount |",
                f"|-----------|--------|",
                f"| Parts | ₹{sum(p.get('line_total', 0) for p in parts):,.2f} |",
                f"| Labor ({labor_hours}h × ₹{labor_rate:,.0f}/h) | ₹{labor_hours * labor_rate:,.2f} |",
                f"| Consumables | ₹{consumables:,.2f} |",
                f"| **Total** | **₹{total:,.2f}** |",
            ])

        if data.technician_notes:
            lines.extend([
                "",
                "---",
                "",
                "## Technician Notes",
                "",
                data.technician_notes,
            ])

        lines.extend([
            "",
            "---",
            "",
            f"*Report generated by TORQ AI Diagnostic Copilot — {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}*",
            "",
            "*⚠️ This report contains demo data. Verify all specifications against manufacturer documentation.*",
        ])

        return "\n".join(lines)
